### ISSUE TITLE
Speed seems slow when inference on custom dataset

### ISSUE THREAD

**Issue by EdwinKuo1337** [yassouali/pytorch_segmentation#100]
Hi, I'm using the pre-trained model you provided on the git hub and inference with my dataset The speed is very slow, I'm getting 1.45 images/sec, and I'm wondering is that normal?

**Comment by yassouali** [comment]
Hi @EdwinKuo1337 maybe try reducing the number of scales used, For instance, instead of [0.75, 1.0, 1.25, 1.5, 1.75, 2.0] try removing the largest scales, like only using 4 / 3 scales
