### ISSUE TITLE
How can I run your code without training? 

### ISSUE THREAD

**Issue by Jian-danai** [yassouali/pytorch_segmentation#12]
I want to test on my own data(images). Can I achieve this?

**Comment by yassouali** [comment]
Yeas you certainly can, You can check some closed issues where people had a similar question, in a nutshell, you need to create a dataloader and train the model on your data.

**Comment by Jian-danai** [comment]
> Yeas you certainly can, You can check some closed issues where people had a similar question, in a nutshell, you need to create a dataloader and train the model on your data.

Thanks for your kind reply, I mean I want to run the prediction on my own images directly without training, just use your trained model, is that possible?

**Comment by yassouali** [comment]
Yes you certainly can, just download the model and run inference by pointing to the images folder and the model's path; but don't expect good results given that it was trained using a different dataset with potentially different data and class distributions.

**Comment by Jian-danai** [comment]
> Yes you certainly can, just download the model and run inference by pointing to the images folder and the model's path; but don't expect good results given that it was trained using a different dataset with potentially different data and class distributions.

Thank you! I installed the requirements and ran the inference.py but I found an error: (predict.py is inference.py, I just renamed it. I saved my images in '/home/bjyang/pytorch_segmentation-master/image' folder. I just downloaded your 'PSPnet.pth' model)

(py36) bjyang@bjyang-U2003:~/pytorch_segmentation-master$ python predict.py --config config.json --model PSPnet.pth --images /home/bjyang/pytorch_segmentation-master/image
Traceback (most recent call last):
  File "predict.py", line 163, in <module>
    main()
  File "predict.py", line 105, in main
    loader = getattr(dataloaders, config['train_loader']['type'])(**config['train_loader']['args'])
  File "/home/bjyang/pytorch_segmentation-master/dataloaders/voc.py", line 93, in __init__
    self.dataset = VOCAugDataset(**kwargs)
  File "/home/bjyang/pytorch_segmentation-master/dataloaders/voc.py", line 51, in __init__
    super(VOCAugDataset, self).__init__(**kwargs)
  File "/home/bjyang/pytorch_segmentation-master/base/base_dataset.py", line 27, in __init__
    self._set_files()
  File "/home/bjyang/pytorch_segmentation-master/dataloaders/voc.py", line 57, in _set_files
    file_list = [line.rstrip().split(' ') for line in tuple(open(file_list, "r"))]
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOCtrainval_11-May-2012/VOCdevkit/VOC2012/ImageSets/Segmentation/train_aug.txt'

What should I do? Does it mean I need to download VOC dataset?
I have checked the reference.py code, but it's hard for me to fix the error. Could you give me some suggestions?

**Comment by yassouali** [comment]
I guess a quick fix is to just pass the parameters manually:
replace lines 105 - 109 with

```python
    MEAN = [0.45734706, 0.43338275, 0.40058118]
    STD = [0.23965294, 0.23532275, 0.2398498]
    to_tensor = transforms.ToTensor()
    normalize = transforms.Normalize(MEAN, STD)
    num_classes = 21
    palette = palette.get_voc_palette(num_classes)
```
and also we'll neet to add an additional import `from utils import palette`.
