### ISSUE TITLE
Training freezes if image has only class zero.

### ISSUE THREAD

**Issue by gustavu92** [yassouali/pytorch_segmentation#18]
I am using this repository with my dataset that has some images that contain only one class and that could be labeled as zero. I was facing a very strange error that even didn't pop up any message. After some time debugging I found that in the file **base_dataset.py** the method **_augmentation** has an while statement that only finish if **label_new.sum() != 0**. So, in some cases this go forever.

**Comment by yassouali** [comment]
Yes, you're right, I added the while loop to avoid empty images when training on PASCAL VOC and I forgot to remove it. just did it, thanks for the heads up.
