### ISSUE TITLE
The outputs is empty

### ISSUE THREAD

**Issue by JennyVVV** [yassouali/pytorch_segmentation#19]
I have trained the PSPnet on the VOC datasets according to your steps, and now I need to test the trained model, so I run the command `python inference.py --config config.json --model ./saved/PSPNet/10-28_05-10/best_model.pth --images test_images`, there are 10 images named *.jpg to be tested, however the outputs is empty, do you know the reason?
`(torch110) jenny@ubuntn:~/pytorch_segmentation$ python inference.py --config config.json --model ./saved/PSPNet/10-28_05-10/best_model.pth --images test_images/

0it [00:00, ?it/s]
`

**Comment by yassouali** [comment]
Hi, from the iterations, it seems no images were found, can you re-check the images file and the images extension, you can also print the variable `image_files` and see if the images were detected.

**Comment by JennyVVV** [comment]
> Hi, from the iterations, it seems no images were found, can you re-check the images file and the images extension, you can also print the variable `image_files` and see if the images were found.

Thanks for your quick reply, I think the problem is that the images are not found. but the code looks correct, `image_files = sorted(glob(os.path.join(args.images, '*.{args.extension}')))` and  I have tried the relative path and absolute path, it doesn't work.  The images needed to be tested are ipg format.
` python inference.py --config config.json --model ./saved/PSPNet/10-28_05-10/best_model.pth --images test_images`
or
`python inference.py --config config.json --model ./saved/PSPNet/10-28_05-10/best_model.pth --images /home/jenny/pytorch_segmentation/test_images`

**Comment by yassouali** [comment]
can you try hard coding the path and the extension (`args.images` and `args.extension`) to see if the error is indeed the image loading

**Comment by JennyVVV** [comment]
> can you try hard coding the path and the extension (`args.images` and `args.extension`) to see if the error is indeed the image loading

Yeah, I have solved this problem after using the absolute path(`home/jenny/pytorch_segmentation/test_images` ) for the `args.images`, there is no `/` before the home, and the image_files is defined as
`image_files = sorted(glob(os.path.join(args.images, '*.'+args.extension)))`

**Comment by ustcychu** [comment]
Hi, I am also trying to train the PSP model on VOC, have you met this problem when executing the train.py? [https://github.com/yassouali/pytorch_segmentation/issues/31](url)
Thank you!
