### ISSUE TITLE
Undefined behaviour with dict.values()

### ISSUE THREAD

**Issue by vltanh** [yassouali/pytorch_segmentation#21]
I keep getting this error when train

```
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "/home/vltanh/pytorch_segmentation/base/base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "/home/vltanh/pytorch_segmentation/trainer.py", line 92, in _train_epoch
    self.batch_time.average, self.data_time.average))
TypeError: unsupported format string passed to dict.__format__
```

I am using Python 3.5.

Thank you.

Edit: It works or doesn't work randomly.
```
 epoch, self.total_loss.average,
 pixAcc, mIoU,
 self.batch_time.average, self.data_time.average
```
I think sometimes it will get weird value making it not suitable for printing?

Edit 2: When I print them out, pixAcc is a dictionary of mean IoU for each class? Also sometimes when I train the pixAcc got swapped with the mean IoU.

Edit 3: Found the problem. It's because you do
```
  pixAcc, mIoU, _ = self._get_seg_metrics().values()
```
This is undefined behaviour since the value is extracted randomly from the dict (chances, maybe 2/3, is that you will get the class_iou as one of the two, or mix them up like I said above. You should fix this. 

Edit 4: When I fixed it I also got error from
```
  for k, v in list(seg_metrics_.items())[:-1]
```
Same problem, you wouldn't know the order of the item in the list. Consider checking this also.

**Comment by yassouali** [comment]
Hi, this is surprising, I've never encountered this problem, can you try `pixAcc, mIoU, _ = list(self._get_seg_metrics().values())`

**Comment by yassouali** [comment]
Its seems that the order of  the returned items is the same as inserting order starting from Python 3.6 (see this [PEP](https://docs.python.org/3/whatsnew/3.6.html#new-dict-implementation) )

So I think no need to change the code, if someone else has the same problem, they can see this issue.
