### ISSUE TITLE
The Pixel_ACC and m_IOU didn't change too much on my own data

### ISSUE THREAD

**Issue by Erichen911** [yassouali/pytorch_segmentation#24]
Hello, recently I meet the some problem My research is  a two class segmentation. I've changed  dataset from voc.py.
My problem is,Even if the losses keep going down,but the Pixel_acc and mean_Iou didn't change from 5th epoch to 50th epoch.The evaluation didn't change too much.I don't know why.Could you tell me this a bug of code or I do something wrong ?
Waiting for your reply.Thank you!

**Comment by yassouali** [comment]
make sure you're dataloader is corrrect, create an instance of the dataloader, fetch some images and display to make sure the process is correct. you can also launch tensorboard to see the prediction and the ground truths.

**Comment by Erichen911** [comment]
![bug](https://user-images.githubusercontent.com/35665175/68765038-d2b12400-0656-11ea-8569-23d761deec97.png)
Sorry I have already checked the thing which you said before,And there's nothing wrong. And the picture shows  the result of poor Pixel_acc and m_IoU. Could you tell me how to improve the bug?

**Comment by yassouali** [comment]
you can try using PSPNet / Deeplab with larger backbones (resnet101 or resnet151)
