### ISSUE TITLE
What self.STD and self.MEAN mean?

### ISSUE THREAD

**Issue by TerauchiTonnnura** [yassouali/pytorch_segmentation#27]
I want to use my own dataset and made myloader.py.
However, I cannot figure out what self.STD and self.MEAN mean.
I need your help about these values and how I can calculate those.

**Comment by yassouali** [comment]
Its the mean the std of the images in your dataset. You can either compute it or simply use the same one as VOC or any other dataset.

To compute the mean / std, let's say you have all of the path to your images in a variable called `filelist`.

```python
mea, std = 0, 0
for f in filelist:
     img = np.asarray(Image.open(f))
     mean += img.mean(axos=(0,1))
     std += img.std(axis=(0,1))
mean, std = mean/len(filelist), std/len(filelist)
```

**Comment by TerauchiTonnnura** [comment]
Thank you for your quick reply.
So you mean, the length of self.STD or self.MEAN represents the RGB channel, right?

**Comment by yassouali** [comment]
Yeah exactly. The mean of each channel across the whole dataset, and their used to normalize the inputs for more stable training.

By the images I meant the inputs, the labels stay unchanged.

**Comment by TerauchiTonnnura** [comment]
OK, I got it.
It was a great help for me.
