### ISSUE TITLE
How to use Pretrained model for Resnet50 backbone in PSPNet 

### ISSUE THREAD

**Issue by saikiran6** [yassouali/pytorch_segmentation#3]
Can I use resent50 pretrained model for training on custom dataset

**Comment by yassouali** [comment]
Hi, the default behavior is using a pretrained backbone (e.g a resnet) that will be automatically downloaded (you have the option in the config file), but if you want to use your own pretrained model, just find the encoder in the definition of the model you're using and load the checkpoint into the encoder part.
