### ISSUE TITLE
train my own data

### ISSUE THREAD

**Issue by starkcn** [yassouali/pytorch_segmentation#30]
deer author:
 your library is very cool! I have reproduced the voc and ade data using this library.But I have a lot of problems when training with my own data set.

VOC data set format：（it show me this）
Detected GPUs: 1 Requested: 1

  0%|                                                                                                     | 0/100 [00:00<?, ?it/s]

ADE：can not  study the charactor of the object.that only study the charactor of the background

**Comment by starkcn** [comment]
my data have 2 labels, include backgroud and object

**Comment by yassouali** [comment]
Hi, can you see what commit are you in ? there is a while loop in base dataset that can cause this, I fixed a the issue weeks ago (commit 08443)

**Comment by starkcn** [comment]
you are really good! i have solved this problem.i have to say your library is really nice!
hope you will have a fine day!thanks a lot!
