### ISSUE TITLE
loss 

### ISSUE THREAD

**Issue by starkcn** [yassouali/pytorch_segmentation#35]
When I use the LovaszSoftmax loss function,that show me this：
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 30, in main
    loss = getattr(losses, config['loss'])(ignore_index = config['ignore_index'])
TypeError: __init__() got an unexpected keyword argument 'ignore_index'

**Comment by yassouali** [comment]
Yes, the argument should be `ignore_index` instead of `ignore`. Fixed, thanks.
