### ISSUE TITLE
How to start training with PSPnet.pth on my dataset?

### ISSUE THREAD

**Issue by TerauchiTonnnura** [yassouali/pytorch_segmentation#37]
Hi.
I want to train from the checkpoint of PSPnet.pth on my dataset. However, it is a matter that the size of output is 21 and that of my data is 4. Can I load the model and change the output size?

**Comment by yassouali** [comment]
Yes you can, simply change the line `self.model.load_state_dict(checkpoint['state_dict'])` to 
`self.model.load_state_dict(checkpoint['state_dict'], strict=False)`

**Comment by TerauchiTonnnura** [comment]
Thank you for the reply.
I tried that, but seems to have no effect.
The error message is like follows.
```
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.master_branch.1.weight: copying a param with shape torch.Size([21, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 512, 1, 1]).
```
Can you solve this?

**Comment by yassouali** [comment]
Hi, you'll need to remove the first layer from the checkpoint, try this:

```python
checkpoint = OrderedDict([(i, j) for i,j in checkpoint.items() if "module.master_branch.1.weight" not in i])
```

**Comment by TerauchiTonnnura** [comment]
Sorry for replying late.
It looks to me that the keys of the checkpoint are these:
- arch
- epoch
- logger
- state_dict
- optimizer
- monitor_best
- config
and not contains "module.master_branch.1.weight".
Where should I put that line?

**Comment by yassouali** [comment]
Oh yeah you're right, you apply that only for the model's weights:

```python
model_state_dict = checkpoint["state_dict"]
model_state_dict = OrderedDict([(i, j) for i,j in model_state_dict.items() if "module.master_branch.1.weight" not in i])

## And then load the model's weights
model.load_state_dict(model_state_dict)
```

**Comment by TerauchiTonnnura** [comment]
I just ignored these:
- module.master_branch.1.weight
- module.master_branch.1.bias
- module.auxiliary_branch.4.weight
- module.auxiliary_branch.4.bias

However, another error occured.
```
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    main(config, args.resume)
  File "train.py", line 44, in main
    trainer.train()
  File "/var/www/workspace/src/base/base_trainer.py", line 106, in train
    results = self._train_epoch(epoch)
  File "/var/www/workspace/src/trainer.py", line 74, in _train_epoch
    self.optimizer.step()
  File "/opt/conda/lib/python3.6/site-packages/torch/optim/sgd.py", line 100, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: The size of tensor a (21) must match the size of tensor b (4) at non-singleton dimension 0
```

I guess this is the error of the config of optimizer, and I removed
`self.optimizer.load_state_dict(checkpoint['optimizer'])`
then process was done regularly.
However, I wonder this is the right way.
Is there another way?

**Comment by MyLtYkRiTiK** [comment]
> I guess this is the error of the config of optimizer, and I removed
> `self.optimizer.load_state_dict(checkpoint['optimizer'])`
> then process was done regularly.
> However, I wonder this is the right way.
> Is there another way?

I don't know is it right, but it works!

**Comment by yassouali** [comment]
reloading the optimizer state dict is not that important, it just reloads the optimizer parameters and current learning rate.

I guess the problem is that the optimizer contains the momentum of the gradients of the original model's weights, which is obviously different. I don't see why this might be a problem. Thank you the correction (sorry, I didn't see your comment earlier)
