### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Rosalyn0211** [yassouali/pytorch_segmentation#38]
Hi，I trianed my own dataset using deeplab. I got AssertionError, but I don't how to fix it.
![TIM截图20191211165500](https://user-images.githubusercontent.com/46714182/70606241-03c14c00-1c37-11ea-8957-5f13f25dacfc.png)
Thank you!

**Comment by Rosalyn0211** [comment]
target.size is torch.Size([8, 200, 200, 3]), output.size is torch.Size([8, 8, 200, 200]). The size of my images is 200*200, and num_classes is 8.

**Comment by yassouali** [comment]
The target's shape need to be [8, 200, 200], in the data loader, where each element is in range [0, 7], indicating the class of the pixel. Check the data loader, you're targets are in the form of images and not segmentation maps

**Comment by Rosalyn0211** [comment]
I have fixed it.Thank you!

**Comment by Gauravi24** [comment]
> I have fixed it.Thank you!

could you please tell how did you fix this issue because i am getting same error

**Comment by PrasadSahana** [comment]
Hi,

I am getting the same error. Can you please describe the solution in detail? @yassouali

**Comment by yassouali** [comment]
Hi @PrasadSahana 

When you have this assertion error, it means that the labels have different dimensions (H and W) than the images, in this case, I think you may have some discrepancy in the preprocessing of the inputs, where you resize or crop the inputs but not the labels. 

Hope this helps.
