### ISSUE TITLE
The training process was inexplicably terminated

### ISSUE THREAD

**Issue by DarrenmondZhang** [yassouali/pytorch_segmentation#42]
Hi , Thanks your quickly reply yesterday.  But I missed a problem again today.  **The training process was inexplicably terminated**

![image](https://user-images.githubusercontent.com/44083987/72200400-0a382300-3484-11ea-916b-456d8aa50bb5.png)

**Comment by DarrenmondZhang** [comment]
My Platform environment is ：
* pytorch:1.2.0
* python:3.7.3
* cuda: 9.2

**Comment by yassouali** [comment]
Hi, 

Can you check the number of epochs ? Do you train to scratch or do you preload a trained model ?
