### ISSUE TITLE
Different directory structure requirement for ADE20K dataloader

### ISSUE THREAD

**Issue by deepakksingh** [yassouali/pytorch_segmentation#45]
The official dataset does not have the annotations/ directory where as the current ade20k dataset file needs that structure.
Do you have any scripts to convert the official dataset folder to the required directory structure?

**Comment by yassouali** [comment]
Hi. Are you talking about this website: http://sceneparsing.csail.mit.edu/
You can download the annotations (Scene Parsing - ADEChallengeData2016.zip) and after extracting it, you'll end up with two folders: images and annotations.

**Comment by deepakksingh** [comment]
Thank you for the quick response.
I was downloading it from here:
https://groups.csail.mit.edu/vision/datasets/ADE20K/
