### ISSUE TITLE
continue the training on the existing model

### ISSUE THREAD

**Issue by GYE19970220** [yassouali/pytorch_segmentation#47]
Thank you very much for your code. Could you please tell me how to continue the training on the existing model.It's a waste of time to start from scratch every time.waiting for your answer ,Thank you very much

**Comment by yassouali** [comment]
Yes of course, all you need to do is point to the save model (`.pth`) with --resume: for examples `python train.py --config config.json --resume saved/model.pth`.

**Comment by GYE19970220** [comment]
Sorry to bother you again. I want to call the model trained by your code in c++,when I use traced to exchange .pth to .pt,code in figure1,it always report the error that Missing key(s) in state_dict and Unexpected key(s) in state_dict in figure 2 and figure 3.I guess it is because of the config.json,but I don’t know how to call the config.json in traced,could you please teach me if you know about that,thank you very much.Looking forward to your reply.



发送自 Windows 10 版邮件应用

发件人: Yassine
发送时间: 2020年2月3日 22:42
收件人: yassouali/pytorch_segmentation
抄送: GYE19970220; Author
主题: Re: [yassouali/pytorch_segmentation] continue the training on theexisting model (#47)

Closed #47.

**Comment by yassouali** [comment]
Hi, I am really sorry, but I've never used `torch.traced`.

Before saving the model as a `.pt`, did you convert the model to `ScriptModule`?
Anyway, If I have time I might take a look.

Good luck for making it work. You can also post your question in the PyTorch forum to see their solutions.
