### ISSUE TITLE
exchange .pth to .pt

### ISSUE THREAD

**Issue by GYE19970220** [yassouali/pytorch_segmentation#49]
Sorry to bother you again. I want to call the model trained by your code in c++,when I use traced to exchange .pth to .pt,code in figure1,it always report the error that Missing key(s) in state_dict and Unexpected key(s) in state_dict in figure 2 and figure 3.I guess it is because of the config.json,but I don’t know how to call the config.json in traced,could you please teach me if you know about that,thank you very much.Looking forward to your reply.
![d842eaf9898760b8c557e8fe4b5745d](https://user-images.githubusercontent.com/42958175/74491269-16415580-4f06-11ea-869d-ac066932a0fe.png)
![6892f0bf690c1b2c15be2f09c0df336](https://user-images.githubusercontent.com/42958175/74491291-20fbea80-4f06-11ea-9a65-4ad031f42b12.png)

![image](https://user-images.githubusercontent.com/42958175/74491330-396c0500-4f06-11ea-8e90-4a609743b382.png)

**Comment by GYE19970220** [comment]
It seems that I only need the "state_dict" value to change the model,but I havn't know how to use it only in the trace code.
![image](https://user-images.githubusercontent.com/42958175/74493365-e9dd0780-4f0c-11ea-8d44-adda9535fcf4.png)

**Comment by GYE19970220** [comment]
I have successfully loaded the "state_dict",but the Missing key(s) in state_dict and the Unexpected key(s) in state_dict doesn't match
![image](https://user-images.githubusercontent.com/42958175/74494990-7d183c00-4f11-11ea-8bdb-1ec42cf6b5d3.png)
![image](https://user-images.githubusercontent.com/42958175/74495054-ad5fda80-4f11-11ea-95be-e84dbb8b0638.png)

**Comment by yassouali** [comment]
Yes, to use the trained model you only need the state_dict, are you sure you're using the same model as the one trained one, a PSPNet with resnet 50. 

You can also try using `net.load_state_dict(chekpoint["state_dict"], strict=False)`
