### ISSUE TITLE
MultiGPU Training not working

### ISSUE THREAD

**Issue by saikiran6** [yassouali/pytorch_segmentation#5]
Hi

Iam not able to train on multiple gpus. Even though I mention "n_gpu": 4 and args.device='0,1,2,3', it only considers gpu 0 and trains the model on gpu 0.

Line no 90 in base_trainer.py is given like this
"device = torch.device('cuda:0' if n_gpu > 0 else 'cpu')"

Thanks

**Comment by yassouali** [comment]
Hi,

If the GPUs are detected by the system (you can see the number of detected GPUs being printed at the beginning of executing the script) I don't see why the data parallelism won't work, can you manually run `export CUDA_VISIBLE_DEVICES=0,1,2,3` before starting the training ? are all the GPUs in the same node ?

**Comment by yassouali** [comment]
Let's close it, if you still encounter some problems you can reopen it.
