### ISSUE TITLE
The difference between multiscale and sliding

### ISSUE THREAD

**Issue by GYE19970220** [yassouali/pytorch_segmentation#50]
Hello,Could you please tell me the difference between multiscale and sliding when run inference?

**Comment by yassouali** [comment]
Multi scale: you use many scales of the same image: 0.5 - 0.75 - 1 - 1.25 - 1.5: get the prediction for all of the scales, interpolate the outputs to original size and then sum them and take the argmax.

Sliding: Say the image is H x W, you take a window of H/3 x W/3 and slide it over the image with a given stride (say 1/3), each time you make a prediction and add to the output,  and then average the areas where we had a overlap.

Multi-scale works much better, Sliding can be used for very large images where we can parallelize the inference.
