### ISSUE TITLE
image shape of inference

### ISSUE THREAD

**Issue by GYE19970220** [yassouali/pytorch_segmentation#53]
Hello,I noticed that the image shape of training pensurehase is 380*380,while in the inference phase ,how to  ensure this shape when enter the image into the model？except the FCN8

**Comment by yassouali** [comment]
When training, we apply random scaling and cropping, so the model is trained to interpret different scales of the image. And in inference, we simulate the same conditions, by passing different scaled versions of the image and aggregate the predictions.

**Comment by yassouali** [comment]
This is implemented in `multi_scale_predict` in the inference scripy, check it out if you want to see the details. The final output has the same shape as the original image.
