### ISSUE TITLE
can't run the files successfully

### ISSUE THREAD

**Issue by gemitrick** [yassouali/pytorch_segmentation#55]
hi I am a green hand for the semantic segmentation .And this is my first try .I just download your code
and try to run them.But there is an error . Could you tell me what to do? Thanks a lot
![微信图片_20200228182738](https://user-images.githubusercontent.com/61414671/75540963-08d4b100-5a58-11ea-8380-e2b57dd0ef8d.jpg)

**Comment by yassouali** [comment]
Can you post your config; I think you didn't chose the right name for the dataloaders, check `dataloaders/__init__.py` for the correct names.
