### ISSUE TITLE
Run on PyTorch1.4 with Cuda10.1

### ISSUE THREAD

**Issue by takuma-n** [yassouali/pytorch_segmentation#57]
Hi,
Thank you for your cool code. I'm now attempting to run your code on PyTorch1.4 environment. I wanted to use ADE20K like dataset, so I modified a config file to use ADE20K as below.
```json
     "train_loader": {
        "type": "ADE20K",
        "args":{
            "data_dir": "../../data/ADEChallengeData2016",
            "batch_size": 6,
            "base_size": 400,
            "crop_size": 380,
            "augment": true,
            "shuffle": true,
            "scale": true,
            "flip": true,
            "rotate": true,
            "blur": false,
            "split": "training",
            "num_workers": 8
        }
    },

    "val_loader": {
        "type": "ADE20K",
        "args":{
            "data_dir": "../../data/ADEChallengeData2016",
            "batch_size": 2,
            "crop_size": 480,
            "val": true,
            "split": "validation",
            "num_workers": 4
        }
    },
```

However, I couldn't run training process. I got the following error message.
```
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [953,0,0] Assertion `t >= 0 && t < n_classes` failed.
```
Or, sometimes error message is like this;
```
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

I found this error happens when I call `loss.backward()`, and it might be related to range of label values. (from this [link)](https://discuss.pytorch.org/t/loss-backward-runtimeerror-cudnn-error-cudnn-status-execution-failed/50457/3)
Actually, when I use 'VOC dataset', it could run. 'VOC dataset' doesn't have `-1` label value. Then, I modified _load_data function in 'ade20.py' as below; 
```python
    def _load_data(self, index):
        image_id = self.files[index]
        image_path = os.path.join(self.image_dir, image_id + '.jpg')
        label_path = os.path.join(self.label_dir, image_id + '.png')
        image = np.asarray(Image.open(image_path).convert('RGB'), dtype=np.float32)
        label = np.asarray(Image.open(label_path), dtype=np.int32) - 1 # from -1 to 149
        # Added
        label[np.where(label == -1)] = 255 # -1 -> 255 (ignore label)
        return image, label, image_id
```

FInally, I seemingly could run your code. But I'm not sure this modification has negative influence to your code. If you know something, let me know. 

Thanks,

**Comment by yassouali** [comment]
No your right, for PASCAL VOC, the ignore index is 255, but for ADE it is -1, so all you need to do is change it in the config file from `ignore_index: 255` to `ignore_index: -1`.

Your solution also works I guess.
