### ISSUE TITLE
could you add a license to this repository?

### ISSUE THREAD

**Issue by dll263** [yassouali/pytorch_segmentation#59]
Your pytorch segmentation implementation looks very interesting, and well done.  It doesn't appear that you have added a license though, which means others can view and fork your repository on GitHub (based on GitHub terms-of-service), but can't actually run the code or do anything else with it.

Would you consider adding a license so your copyright and intended fair use by others is clear?

See these pages for details:

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
https://choosealicense.com

Thanks

**Comment by yassouali** [comment]
Done, thank you for raising this issue.

**Comment by dll263** [comment]
Thanks!
