### ISSUE TITLE
Anyone can share the pretrained model ? I can't connect to the dropbox!

### ISSUE THREAD

**Issue by Linfengscat** [yassouali/pytorch_segmentation#63]

**Comment by yassouali** [comment]
HI,

Here is a google drive link: https://drive.google.com/open?id=1t_m5QydTemZk7VZB8269HcdG7zq-7V4O

Hopes this works.

**Comment by fnbory** [comment]
hi,Could you please share the model? I can't connect to the dropbox ,too

**Comment by fnbory** [comment]
> HI,
> 
> Here is a google drive link: https://drive.google.com/open?id=1t_m5QydTemZk7VZB8269HcdG7zq-7V4O
> 
> Hopes this works.

Could you share the model on google drive again? It seems now  can not work

**Comment by yassouali** [comment]
@fnbory here is a new link: https://github.com/yassouali/pytorch_segmentation/releases/download/v0.1/PSPnet.pth
