### ISSUE TITLE
Inference without CUDA

### ISSUE THREAD

**Issue by AlexanderSenf** [yassouali/pytorch_segmentation#66]
I was getting a CUDA related error when trying to run inference without CUDA: https://github.com/yassouali/pytorch_segmentation/blob/master/inference.py#L116

If I change this line to: `checkpoint = torch.load(args.model, map_location=device)` it seems to work, the `device` automatically detects the presence of a gpu.

**Comment by yassouali** [comment]
Thank you for this feedback, I just corrected the error.
