### ISSUE TITLE
About resume the checkpoint.pth

### ISSUE THREAD

**Issue by hhloverr** [yassouali/pytorch_segmentation#67]
When I want to resume the checkpoint.pth, I have a problem: 
"KeyError: 'logger'", and I find that there is no the key "logger" in save_checkpoint function.
So I delete the  "self.train_logger = checkpoint['logger']" in resume_checkpoint.
After that, the code cannot still train.
How can I modify the code?
Thank you~ Your code is very helpful.

**Comment by hhloverr** [comment]
After I delete the "self.train_logger = checkpoint['logger']" in resume_checkpoint, it is OK.
It cannot work because of "learning_rate=0". lol~
Thank you!

**Comment by yassouali** [comment]
Yes, it is better to ignore reloading the logger, thanks.
