### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rurubaobao** [yassouali/pytorch_segmentation#7]
![捕获](https://user-images.githubusercontent.com/45089528/63776626-525f0a80-c914-11e9-9aa8-aa1fc6ac2e61.PNG
Hello I have this error

**Comment by yassouali** [comment]
Hi,

I've never encountered this problem, are you using torch 1.1.0 ? did you see if the script works in a new env ? I think there is some problem with the packages.

**Comment by rurubaobao** [comment]
Thank you very much for your timely reply. The solution to this problem is pip install future. However, when I solve this problem, a new problem appears.
File "C:/Users/lenovo/PycharmProjects/fr/pytorch_segmentation-master/train.py", line 61, in <module>
    main(config, args.resume)
  File "C:/Users/lenovo/PycharmProjects/fr/pytorch_segmentation-master/train.py", line 42, in main
    trainer.train()
  File "C:\Users\lenovo\PycharmProjects\fr\pytorch_segmentation-master\base\base_trainer.py", line 98, in train
    results = self._train_epoch(epoch)
  File "C:\Users\lenovo\PycharmProjects\fr\pytorch_segmentation-master\trainer.py", line 49, in _train_epoch
    for batch_idx, (data, target) in enumerate(tbar):
  File "C:\Users\lenovo\AppData\Local\conda\conda\envs\fr\lib\site-packages\tqdm\_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "C:\Users\lenovo\PycharmProjects\fr\pytorch_segmentation-master\base\base_dataloader.py", line 76, in __iter__
    self.preload()
  File "C:\Users\lenovo\PycharmProjects\fr\pytorch_segmentation-master\base\base_dataloader.py", line 64, in preload
    self.next_input, self.next_target = next(self.loaditer)
  File "C:\Users\lenovo\AppData\Local\conda\conda\envs\fr\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "C:\Users\lenovo\AppData\Local\conda\conda\envs\fr\lib\site-packages\torch\utils\data\dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "C:\Users\lenovo\PycharmProjects\fr\pytorch_segmentation-master\base\base_dataset.py", line 140, in __getitem__
    label = torch.from_numpy(np.array(label, dtype=np.int32)).long()
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

**Comment by yassouali** [comment]
Hi, I think the problem lies in the data type of the labels, can you check the type of your labels, there must be some error when loading the labels, can you post the code you use for loading them.

**Comment by rurubaobao** [comment]
Hello, I'm using voc data. When I tested on ubuntu, it worked fine, but when I tested on Windows, I had the above problem.I was wondering if you've ever tested Windows?

**Comment by yassouali** [comment]
No not in windows unfortunately, maybe the numpy version is not the correct one (or torch), sadly I am not seeing the cause of the error, try loading some labels manually in a python shell / jupyter using the code in `voc.py` and `base_dataset.py` and see if you can find the root cause.

**Comment by rurubaobao** [comment]
Thank you for your help. I have solved it.I have another question, how to train my data.My data is two classes, like this.Where should I make changes
![0](https://user-images.githubusercontent.com/45089528/63918766-ebeeff00-ca6f-11e9-8a5a-79920dc07346.png)

**Comment by yassouali** [comment]
You need to create your dataloader, like the ones provided in `dataloaders/`, you'll need to implement to function `_set_files`: sets the file paths for the labels and the images, and `_load_data` loads the labels and images given an index.

And then create a loader and with the correct parameters (num classes = 2 for instance) and then change the config file and you're done.

**Comment by rurubaobao** [comment]
Thank you, I have implemented it, however, I have a problem with the program when I replace Crossentropy with DiceLoss.
Traceback (most recent call last):
  File "C:/Users/lenovo/PycharmProjects/fr/pytorch_segmentation-master/train.py", line 61, in <module>
    main(config, args.resume)
  File "C:/Users/lenovo/PycharmProjects/fr/pytorch_segmentation-master/train.py", line 30, in main
    loss = getattr(losses, config['loss'])(ignore_index = config['ignore_index'])
TypeError: __init__() got an unexpected keyword argument 'ignore_index'

By the way, my numclass is 2, do I need to modify the following function?

palette.py
def get_voc_palette(num_classes):
    n = num_classes
    palette = [0]*(n*3)
    for j in range(0,n):
            lab = j
            palette[j*3+0] = 0
            palette[j*3+1] = 0
            palette[j*3+2] = 0
            i = 0
            while (lab > 0):
                    palette[j*3+0] |= (((lab >> 0) & 1) << (7-i))
                    palette[j*3+1] |= (((lab >> 1) & 1) << (7-i))
                    palette[j*3+2] |= (((lab >> 2) & 1) << (7-i))
                    i = i + 1
                    lab >>= 3
    return palette

**Comment by yassouali** [comment]
Just remove the `ignore_index`, given that dice loss in `utils\losses.py` doesn't take as input argument `ignore_index`, for the function creating the palette, you don't need to change it, unless you already have a specific palette you want to use

**Comment by rurubaobao** [comment]
when I  remove the ignore_index, I have another problem

Traceback (most recent call last):
  File "C:/Users/lenovo/PycharmProjects/fr/pytorch_segmentation-master/train.py", line 61, in <module>
    main(config, args.resume)
  File "C:/Users/lenovo/PycharmProjects/fr/pytorch_segmentation-master/train.py", line 40, in main
    train_logger=train_logger)
  File "C:\Users\lenovo\PycharmProjects\fr\pytorch_segmentation-master\trainer.py", line 14, in __init__
    super(Trainer, self).__init__(model, loss, resume, config, train_loader, val_loader, train_logger)
  File "C:\Users\lenovo\PycharmProjects\fr\pytorch_segmentation-master\base\base_trainer.py", line 35, in __init__
    self.loss.to(self.device)
  File "C:\Users\lenovo\AppData\Local\conda\conda\envs\fr\lib\site-packages\torch\nn\modules\module.py", line 386, in to
    return self._apply(convert)
AttributeError: 'torch.device' object has no attribute '_apply'

**Comment by yassouali** [comment]
I just took a look, there is indeed a problem with the loss when the ignore index is say 255, the one hot target is of different size than the output, which triggers a device error. 

Just pushed a simple correction, might need to fix it for good with gradient stopping, but for now it works, this time don't remove ignore index.

**Comment by rurubaobao** [comment]
Thank you very much, but now I have a problem，I use PSPNet,loss is crossentropy.numclass =2 and I use my data.the problem is 
## Info for epoch 10 ## 
         val_loss       : 0.09203
         Pixel_Accuracy : 0.529
         Mean_IoU       : 0.265
         Class_IoU      : {0: 0.53, 1: 0.0}
。。。
## Info for epoch 55 ## 
         val_loss       : 0.01977
         Pixel_Accuracy : 0.53
         Mean_IoU       : 0.265
         Class_IoU      : {0: 0.53, 1: 0.0}

         ## Info for epoch 60 ## 
         val_loss       : 0.01939
         Pixel_Accuracy : 0.53
         Mean_IoU       : 0.265
         Class_IoU      : {0: 0.53, 1: 0.0}

mydata is like this 
image
![0](https://user-images.githubusercontent.com/45089528/64000866-2a9cbc00-cb39-11e9-9c5d-144cc72e31f2.png)

mask
![0](https://user-images.githubusercontent.com/45089528/64000957-620b6880-cb39-11e9-8dc2-22ba6a2cb01d.png)

and mydataloader is like voc.
class VOCDataset(BaseDataSet):
    """
    Pascal Voc dataset
    http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar
    """
    def __init__(self, **kwargs):
        self.num_classes = 2
        self.palette = palette.get_voc_palette(self.num_classes)
        super(VOCDataset, self).__init__(**kwargs)

    def _set_files(self):
        self.root = os.path.join(self.root, 'VOCdevkit/VOC2012')
        self.image_dir = os.path.join(self.root, 'JPEGImages')
        self.label_dir = os.path.join(self.root, 'SegmentationClass')

        file_list = os.path.join(self.root, "ImageSets/Segmentation", self.split + ".txt")
        self.files = [line.rstrip() for line in tuple(open(file_list, "r"))]
    
    def _load_data(self, index):
        image_id = self.files[index]
        image_path = os.path.join(self.image_dir, image_id + '.png')
        label_path = os.path.join(self.label_dir, image_id + '.png')
        image = np.asarray(Image.open(image_path), dtype=np.float32)
        label = np.asarray(Image.open(label_path).convert('L'), dtype=np.int32)
        image_id = self.files[index].split("/")[-1].split(".")[0]
        return image, label, image_id
class VOC(BaseDataLoader):
    def __init__(self, data_dir, batch_size, split, crop_size=None, base_size=None, scale=True, num_workers=1, val=False,
                    shuffle=False, flip=False, rotate=False, blur= False, augment=False, val_split= None, return_id=False):
        
        self.MEAN = [0.45734706, 0.43338275, 0.40058118]
        self.STD = [0.23965294, 0.23532275, 0.2398498]

        kwargs = {
            'root': data_dir,
            'split': split,
            'mean': self.MEAN,
            'std': self.STD,
            'augment': augment,
            'crop_size': crop_size,
            'base_size': base_size,
            'scale': scale,
            'flip': flip,
            'blur': blur,
            'rotate': rotate,
            'return_id': return_id,
            'val': val
        }
   if  split in ["train", "trainval", "val", "test"]:
            self.dataset = VOCDataset(**kwargs)
        else: raise ValueError(f"Invalid split name {split}")
        super(VOC, self).__init__(self.dataset, batch_size, shuffle, num_workers, val_split)

**Comment by yassouali** [comment]
Did you create you own dataloader, with the correct paths (for example for VOC, the images are in `VOCdevkit/VOC2012/JPEGImages` and the labels in `VOCdevkit/VOC2012/SegmentationClass`) you need to adjust the variables for you dataset.

**Comment by rurubaobao** [comment]
Hello, I put the data under the path of voc.py, and made train. txt,val. txt and trainval. txt.The difference is that my number of categories is 2. I would like to ask what else I need to correct?
[新建文本文档.TXT](https://github.com/yassouali/pytorch_segmentation/files/3563039/default.TXT)

![捕获](https://user-images.githubusercontent.com/45089528/64071014-17a5fb00-cca3-11e9-8b7b-f0ab045096e7.PNG)
![捕获](https://user-images.githubusercontent.com/45089528/64071017-2f7d7f00-cca3-11e9-935f-64b4917aff76.PNG)
![捕获](https://user-images.githubusercontent.com/45089528/64071021-4623d600-cca3-11e9-85c7-f987a2e0690f.PNG)

**Comment by yassouali** [comment]
For the number of classes, there is a class attribute in `class VOCDataset` called `self.num_classes`, set it to 2, other that that you're good to go (you might also want to calculate the `mean` and `std` of your dataset, but you can do it afterwards)

**Comment by rurubaobao** [comment]
OK，Thanks.

**Comment by Erichen911** [comment]
Hello, recently I meet the same problem like yours.My research is extremely same as your research.I use the same model ,the same loss function,And it's also a two class segmentation.My problem is the same as yours.Even if the losses keep going down,but the Pixel_acc and mean_Iou didn't change from 5th epoch to 50th epoch.The evaluation didn't change too much.I don't know why.Could you tell is this a bug of code or I do something wrong ?
Waiting for your reply.Thank you!

**Comment by rurubaobao** [comment]
Hello, I just saw it recently. Have you solved this problem？
