### ISSUE TITLE
Pretrained Resnet models cannot be downloaded

### ISSUE THREAD

**Issue by davidblom603** [yassouali/pytorch_segmentation#70]
When I try to download the zip files (for example https://hangzh.s3.amazonaws.com/encoding/models/resnet101-2a57e44d.zip), I get a 403 Access Denied error.

**Comment by Damanpreet** [comment]
@davidblom603 I am facing the same issue.

**Comment by Damanpreet** [comment]
@aicaffeinelife I saw your comments in the issue that you use ResNet101 backbone network.
Do you have the pre-trained checkpoints saved somewhere and can provide them?

**Comment by aicaffeinelife** [comment]
@Damanpreet I tried searching for a trained checkpoint but I didn't find one.  I went with [PyTorch-Encoding](https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html) for implementing my own algorithms.

However if you only need the pre-trained Resnet101 backbone then you can download them from [here](https://github.com/hszhao/semseg). 

Hope this helps.

**Comment by bufferXia** [comment]
> @aicaffeinelife I saw your comments in the issue that you use ResNet101 backbone network.
> Do you have the pre-trained checkpoints saved somewhere and can provide them?

I had downloaded the Resnet50 pretrained model some day before. I don't know where I can upload the model. So, if you want the Resnet50 model, you I can send to your e-mail. The reason why you can not download the pretrained model is the author closed it.
https://github.com/zhanghang1989/PyTorch-Encoding/issues/273

**Comment by yassouali** [comment]
The checkpoints were updated by @szatidani.

**Comment by Damanpreet** [comment]
Thank you all very much!

**Comment by sym330** [comment]
https://github.com/LikeLy-Journey/SegmenTron/releases/
