### ISSUE TITLE
Can't plot the learning rate curve

### ISSUE THREAD

**Issue by MHandZQ** [yassouali/pytorch_segmentation#79]
Hi,

Thanks for building this cool library and I'm sorry to bother you, I've been trying to run lr_scheduler.py, but there're something wrong like this:
`lr_scheduler(optimizer, i, epoch)`
`TypeError: 'OneCycle' object is not callable`
I really don’t know the meaning of this line of code：
`lr_scheduler(optimizer, i, epoch)`
When I canccel this line of code, the result is:
![Figure_1](https://user-images.githubusercontent.com/30924400/89243276-2117b000-d636-11ea-9ba2-fd25e16a752a.png)
Could you tell how to solve this problem

**Comment by yassouali** [comment]
Hi @MHandZQ 

The learning rate schedulers are the same as in pytorch since they inherit from `_LRScheduler`.
After creating a lr scheduler, you can then call step method of the class.

```python
# init
lr_scheduler =  lr_scheduler(optimizer, i, epoch)

for i in range(iterations):
       lr_scheduler.step(i)
       # to get the current lr
       current_lr = optimizer.param_groups[0]['lr']
```
