### ISSUE TITLE
"Expected more than 1 value per channel when training"

### ISSUE THREAD

**Issue by fdujay** [yassouali/pytorch_segmentation#8]
When training on VOC, I met this error.
I want to know how to solve it, does anybody know it？
Maybe my batchsize=4 is not suitable, but 8 or 16 is too large for my gpu...

**Comment by yassouali** [comment]
Does this happen after some training iterations (last iteration in the first epoch) or from the beginning ? after some training iterations it may be the case that in the last iteration you'll endup with only one example left, try a batch size of 6 (or test if the batch == 1 in trainer and duplicate the input)
