### ISSUE TITLE
Inference using CPU

### ISSUE THREAD

**Issue by ningCe** [yassouali/pytorch_segmentation#81]
Thanks for your great job, it helps me a lot.
When I try to do inference, it worked fine using cuda, but when I change device to cpu, 
    # device = torch.device('cuda:0' if len(availble_gpus) > 0 else 'cpu')
    device = torch.device('cpu')

errors happened:

 File "inference.py", line 174, in <module>
    main()
  File "inference.py", line 146, in main
    prediction = multi_scale_predict(model, input, scales, num_classes, device)
  File "inference.py", line 70, in multi_scale_predict
    scaled_prediction = upsample(model(scaled_img).cpu())
  File "D:\Qiuyu\anaconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Qiuyu\anaconda\lib\site-packages\torch\nn\parallel\data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
**RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu**
  0%|                                                                      | 0/1547 [00:00<?, ?it/s]

how should I revised the code to do inference on cpu?

**Comment by yassouali** [comment]
Hi @ningCe 

I think this error here comes from using Data-Parallel, can you comment the lines where the model is wrapped with data parallel and see if it works?

**Comment by ningCe** [comment]
Yes, it works.

 I comment data parallel lines and find the layer names between model and checkpoint don't match, all layer names in checkpoint have additional "module." in front of layer names in model.(Maybe still due to Data-Parallel when model training)

#if 'module' in list(checkpoint.keys())[0] and not isinstance(model, torch.nn.DataParallel):
#    model = torch.nn.DataParallel(model)

and I processed the situation just this way:

    checkpoint_cpu = {}
    for key, value in checkpoint.items():
        key_cpu = key[7:]
        checkpoint_cpu[key_cpu] = value
    model.load_state_dict(checkpoint_cpu)

and it works normally, but I  haven't confirm whether performance is consistent with cuda.

**Comment by yassouali** [comment]
Thanks @ningCe, fixed this.
