### ISSUE TITLE
Freeze backbone not working

### ISSUE THREAD

**Issue by sovit-123** [yassouali/pytorch_segmentation#83]
Even if I use `"freeze_backbone": true` in the config file for VGG16, still it is showing 134 million trainable parameters.

**Comment by yassouali** [comment]
Hi @sovit-123, sorry for the delay.

You were right, some models were missing the call for `set_trainable` to freeze the backbone.
Just pushed the correction.


Thanks.

**Comment by sovit-123** [comment]
Thanks for the update. Will check it out.
