### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by RishiTejaMadduri** [yassouali/pytorch_segmentation#85]
Hey!
Thank you for the code. Its very helpful. I was trying to run your code on azure cloud platform and I kept getting Segmentation fault (core dumped) error. I get it after the model has been printed. Do you have any solution for this?

I am using UNet with VOC dataset. Everything loads correctly and works well on my laptop but on cloud, it fails.

**Comment by yassouali** [comment]
Hi @RishiTejaMadduri ;

I think this is more due the env, make sure all the dependencies are installed (or try other versions), and the instance have enough RAM.

**Comment by RishiTejaMadduri** [comment]
Hi @yassouali Thank you for getting back to me. It was due to Tensorboard and for now I just commented out all the writer parts now it working very well.
