### ISSUE TITLE
GPU memory 

### ISSUE THREAD

**Issue by holyseven** [yassouali/pytorch_segmentation#89]
I found that one GPU uses much more memory than others. Is it normal ?

![image](https://user-images.githubusercontent.com/13829174/96154412-59deda00-0f41-11eb-8863-fb7350d02b8f.png)

with the configuration on VOC: https://github.com/yassouali/pytorch_segmentation#config-file-format, except batch_size = 16, n_gpu = 4, and DeepLab.

**Comment by yassouali** [comment]
Hi @holyseven 

I did not observe this, are you training with synch bn, can you try without it? can you also maximize the memory usage by incresing the batch size and seeing if this helps?

**Comment by holyseven** [comment]
Hi @yassouali 

I was training with sync bn with slightly modified codes. I wrongly set the `num_worker` to 0. Reset it to 8 works normally on pascal voc. Not sure if it is the reason.

Thanks. Closed it.
