### ISSUE TITLE
ValueError: Invalid split name train_aug

### ISSUE THREAD

**Issue by starkcn** [yassouali/pytorch_segmentation#9]
I want to train my own data.But it often meet some problem.
"split": "train_aug", // Split to use, depend of the dataset and "split": "val", i dont know how to set it.that make me meet a lot questions.Hope you will me some suggestions!my data just like ade20k.

**Comment by yassouali** [comment]
It is up to you, It better to not reuse an existing dataloader for you dataset, create a new one with the correct path, splits, number of classes ..., just use the existing ones as an example.

**Comment by starkcn** [comment]
I have a poor ability to write code and I want to train directly in the official dataset format. I made the dataset production according to the dataset format of ade20k.I hope to carry out my own data set training under the premise of modifying the code structure as little as possible. I am not specializing in deep learning research, but using the model to apply in my own field.So, I hope that you can give me guidance on the dataset, I would be grateful!

**Comment by yassouali** [comment]
Ok, what error or problem do you currently have? can you share with me you dataset structure ?

**Comment by starkcn** [comment]
Thank you ! Dataset structure:  data----ADEChallengeData2016---annotation--train/validation ,
                                                                data----ADEChallengeData2016--images-- train/validation

When I execute the training command, I will be prompted with the following error message.
  Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 22, in main
    train_loader = get_instance(dataloaders, 'train_loader', config)
  File "train.py", line 16, in get_instance
    return getattr(module, config[name]['type'])(*args, **config[name]['args'])
  File "/home/caffe/jack/pytorch_segmentation-master/dataloaders/ade20k.py", line 61, in __init__
    self.dataset = ADE20KDataset(**kwargs)
  File "/home/caffe/jack/pytorch_segmentation-master/dataloaders/ade20k.py", line 21, in __init__
    super(ADE20KDataset, self).__init__(**kwargs)
  File "/home/caffe/jack/pytorch_segmentation-master/base/base_dataset.py", line 27, in __init__
    self._set_files()
  File "/home/caffe/jack/pytorch_segmentation-master/dataloaders/ade20k.py", line 28, in _set_files
    else: raise ValueError(f"Invalid split name {self.split}")
ValueError: Invalid split name train

**Comment by yassouali** [comment]
you need to change the split name, the split depend on the dataset used, for ADE20K, there is two types: training and validation, you can check them in `dataloaders`, for ADE20K, if you go to `dataloaders/ade20k.py` in `_set_files` you'll find `if self.split in  ["training", "validation"]`

**Comment by starkcn** [comment]
I looked at this code file, but I don't know which file is called by split, and what is the path to this file? I have separated the data for training and testing, and I have made the corresponding txt file, but I don't know if this txt file is called in ade.py.

**Comment by starkcn** [comment]
I tried it again and it was already running. Thank you very much for your help! Can I add you a contact method? My email address is jk800756@163.com

**Comment by yassouali** [comment]
No problem, you can contact me at ouali.yasine@gmail.com it you have any questions.
