### ISSUE TITLE
Dataset Cityscapes with model Segnet

### ISSUE THREAD

**Issue by Phulieu** [yassouali/pytorch_segmentation#90]
Here is my error:
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 22, in main
    train_loader = get_instance(dataloaders, 'train_loader', config)
  File "train.py", line 16, in get_instance
    return getattr(module, config[name]['type'])(*args, **config[name]['args'])
TypeError: 'module' object is not callable

Here is my config.jston
{
    "name": "SegNet",
    "n_gpu": 1,
    "use_synch_bn": true,

    "arch": {
        "type": "SegNet",
        "args": {
            "backbone": "resnet50",
            "freeze_bn": false,
            "freeze_backbone": false
        }
    },

    "train_loader": {
        "type": "cityscapes",
        "args":{
            "data_dir": "/dataset",
            "batch_size": 8,
            "base_size": 1024,
            "crop_size": 512,
            "augment": true,
            "shuffle": true,
            "scale": true,
            "flip": true,
            "rotate": true,
            "blur": false,
            "split": "train_aug",
            "num_workers": 8
        }
    },

    "val_loader": {
        "type": "cityscapes",
        "args":{
            "data_dir": "/dataset",
            "batch_size": 8,
            "crop_size": 512,
            "val": true,
            "split": "val",
            "num_workers": 4
        }
    },

    "optimizer": {
        "type": "SGD",
        "differential_lr": true,
        "args":{
            "lr": 0.01,
            "weight_decay": 1e-4,
            "momentum": 0.9
        }
    },

    "loss": "CrossEntropyLoss2d",
    "ignore_index": 255,
    "lr_scheduler": {
        "type": "Poly",
        "args": {}
    },

    "trainer": {
        "epochs": 80,
        "save_dir": "saved/",
        "save_period": 10,
  
        "monitor": "max Mean_IoU",
        "early_stop": 10,
        
        "tensorboard": true,
        "log_dir": "saved/runs",
        "log_per_iter": 20,

        "val": true,
        "val_per_epochs": 10
    }
}

**Comment by yassouali** [comment]
HI @Phulieu 

The error comes from `"type": "cityscapes"`.
The name of the class is `CityScapes`.
