### ISSUE TITLE
config error？

### ISSUE THREAD

**Issue by ShiMinghao0208** [yassouali/pytorch_segmentation#93]
I use my json and copy totally the sample json code， there is a same error：
![image](https://user-images.githubusercontent.com/53176521/97414960-96e29d80-193f-11eb-93e6-03f5c28dd545.png)
![QQ图片20201029220708](https://user-images.githubusercontent.com/53176521/97584573-20bf6300-1a33-11eb-80ba-a39228a24b93.png)

**Comment by yassouali** [comment]
Hi @ShiMinghao0208 

This error is weird :) what python version are you using ? can you re-run with just `python train.py` ?

**Comment by ShiMinghao0208** [comment]
> Hi @ShiMinghao0208
> 
> This error is weird :) what python version are you using ? can you re-run with just `python train.py` ?
python version is 2.7.17，just run `python train.py` result i have upgrade.
i am sorry to disturb u

**Comment by yassouali** [comment]
Hi @ShiMinghao0208 

For this repo, you'll need python version > 3.5, this explains the erro since f-strings are python-3 specific.
