### ISSUE TITLE
I wonder how can i apply this to a new non-public dataset, please.

### ISSUE THREAD

**Issue by liyanping0317** [yassouali/pytorch_segmentation#96]

**Comment by yassouali** [comment]
Hi @liyanping0317 

You'll need to just create your data loader class (like the ones in `dataloaders/`) to load the images and the labels. Then simply call the loader for training.

**Comment by liyanping0317** [comment]
@yassouali Thanks a lot. I created my own dataloader classs, but when i called the train, there was an error like cuDNN error: CUDNN_STATUS_INTERNAL_ERROR. I seach on the internet, it seems to be realated to the number of objects to be segmented. Is there something else need to be change except the num_classes in the dataloader classs.

**Comment by yassouali** [comment]
@liyanping0317 make sure to change the number of classes in the config file depending on your use case.

**Comment by liyanping0317** [comment]
@yassouali For some unknow reasons, there is always an error like this:TypeError: zip argument #2 must support iteration. I tried every method i can search on the internet, but stil couldnot solve it. May i ask for your help...

**Comment by yassouali** [comment]
Hi @liyanping0317 

Can you post the code that causes this error?

**Comment by Unrivaled2** [comment]
@liyanping0317 I have same problem. May I ask you your solution later?

**Comment by Unrivaled2** [comment]
> Hi @liyanping0317
> 
> Can you post the code that causes this error?

I have the same problem. My dataloader code  is shown below
`import torch
import cv2
from PIL import Image
from glob import glob
from torch.utils.data import Dataset
from torchvision import transforms


class TC_Race_Dataset(BaseDataSet):
    def __init__(self, **kwargs):
        self.num_classes = 9
        self.palette = palette.tc_race_palette
        super(TC_Race_Dataset, self).__init__(**kwargs)

    def _set_files(self):
        if self.split in ["training", "validation"]:
            self.image_dir = os.path.join(self.root, 'images', self.split)
            self.label_dir = os.path.join(self.root, 'annotations', self.split)
            self.files = [os.path.basename(path).split('.')[0] for path in glob(self.image_dir + '/*.tif')]
        else:
            raise ValueError(f"Invalid split name {self.split}")

    def _load_data(self, index):
        image_id = self.files[index]
        image_path = os.path.join(self.image_dir, image_id + '.tif')
        label_path = os.path.join(self.label_dir, image_id + '.png')
        image = np.asarray(Image.open(image_path), dtype=np.float32)
        # print(image)
        label = np.asarray(Image.open(label_path), dtype=np.int32)
        #print(label)
        return image, label, image_id


class TC_RACE(BaseDataLoader):
    def __init__(self, data_dir, batch_size, split, crop_size=None, base_size=None, scale=True, num_workers=1,
                 val=False,
                 shuffle=False, flip=False, rotate=False, blur=False, augment=False, val_split=None, return_id=False):
        self.MEAN = [0.5,0.5,0.5,0.5]
        self.STD = [0.5,0.5,0.5,0.5]

        kwargs = {
            'root': data_dir,
            'split': split,
            'mean': self.MEAN,
            'std': self.STD,
            'augment': augment,
            'crop_size': crop_size,
            'base_size': base_size,
            'scale': scale,
            'flip': flip,
            'blur': blur,
            'rotate': rotate,
            'return_id': return_id,
            'val': val
        }

        self.dataset = TC_Race_Dataset(**kwargs)
        super(TC_RACE, self).__init__(self.dataset, batch_size, shuffle, num_workers, val_split)`

The traceback is:
`  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "/home/ljt21/race/pytorch_segmentation/base/base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "/home/ljt21/race/pytorch_segmentation/trainer.py", line 70, in _train_epoch
    loss.backward()
  File "/home/ljt21/anaconda3/envs/tc_race/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ljt21/anaconda3/envs/tc_race/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR`

I'd appreciate it if you could help me

**Comment by liyanping0317** [comment]
@Unrivaled2 I think the direct reason of  your problem is that the class numbers in your label is bigger than you set in self.num_classes, but deeply may be because your method of reading label is not correctly.  In some dataset, the label is number range from 1 to something, but some maybe decoded like ronge from 100 to 900, and others maybe grayscale image， but in this code label format must be the first one, so np.asarray is not always be the right way. You need to translate your label name to adapt the first way, like "label = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE)". That's my advice.

**Comment by liyanping0317** [comment]
@yassouali Thanks a lot , i have saved my problem.
