### ISSUE TITLE
CUDA out of memory when running inference locally

### ISSUE THREAD

**Issue by lccatala** [yassouali/pytorch_segmentation#97]
Hi, I'm trying to integrate the inference script with a ROS node to run locally, but my GPU doesn't have enough free memory (GTX 1060). It shouldn't need that much memory just to run inference, so I'm wondering if there is any way of reducing it's use. This is the output I get:
`RuntimeError: CUDA out of memory. Tried to allocate 1.70 GiB (GPU 0; 5.93 GiB total capacity; 2.59 GiB already allocated; 1.08 GiB free; 3.51 GiB reserved in total by PyTorch)
`

**Comment by yassouali** [comment]
Hi @lccatala maybe try reducing the number of scales used, For instance, instead of `[0.75, 1.0, 1.25, 1.5, 1.75, 2.0]` try removing the largest scales, like only using 4 scales `[0.75, 1.0, 1.25, 1.5]`
