### ISSUE TITLE
inference have a problem

### ISSUE THREAD

**Issue by QianyuZhai** [yassouali/pytorch_segmentation#98]
thanks for your code. I trained PSPNet get a good result in tensorboard. In tensorboard , the result of prediction images is pretty good , but when i use the inference , i have to ues 'strick=false'  to ensure load my weights,and the result of prediction images so terrible than images in tesnorboard . i want to know what is my problem.Looking forward your reply!

**Comment by yassouali** [comment]
Hi @QianyuZhai, I think the problem is the model is loaded, make sure you are using the same model you used in training, and make sure the loading is correct without any `strict=false`.

**Comment by QianyuZhai** [comment]
Thanks for your reply ! I solve the problem by your way.
